default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE'] %>
  password: <%= ENV['DEVELOPMENT_DATABASE_PASSWORD'] %>

test: &test
  <<: *default
  database: <%= ENV['TEST_DATABASE'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %>
